version: "3"

vars:
  PATH_LOCAL: "{{ .HOME }}/.local"
  PATH_LOCAL_BIN: "{{ .PATH_LOCAL }}/bin"
  PATH_CONFIG: "{{ .HOME }}/.config"
  PATH_APPLICATION_SUPPORT: "{{ .HOME }}/Library/Application Support"

tasks:
  # operations
  # ---------------------------------------------------------------------------
  update/submodules:
    desc: Update git submodules
    cmds:
      - git submodule update --init --remote
      - git status

  ":collect":
    desc: Collect all configs
    deps:
      - collect/git/config
      - collect/k9s/config
      - collect/neovim/config
      - collect/tmux/config
      - collect/zsh/config

  ":install":
    desc: Install all environments
    deps:
      - install/bat/config
      - install/git/config
      - install/k9s/config
      - install/neovim/env
      - install/tmux/env
      - install/zsh/env
      - install/python/playground
      - install/toolkit/python-tools
      - install/toolkit/repo-scripts

  # helper functions
  # ---------------------------------------------------------------------------
  helper/checkout-submodule:
    label: checkout-submodule[{{ .DIR }}]
    internal: true
    cmds:
      - git submodule update --init {{ .DIR }}
    status:
      - "[[ -n $SKIP_SUBMODULE_CHECKOUT ]]"

  helper/copy-config-dir:
    label: copy-config-dir[{{ .NAME }}]
    internal: true
    vars:
      DIR: "{{ .DIR | default .PATH_CONFIG }}"
    cmds:
      - mkdir -p '{{ .DIR }}/{{ .NAME }}'
      - cp -vaf 'config/{{ .NAME }}/'* '{{ .DIR }}/{{ .NAME }}/'

  helper/ensure-config-file-dir:
    label: ensure-dir[{{ .DIR }}]
    internal: true
    vars:
      DIR:
        sh: dirname {{ .FILE }}
    status:
      - "[[ -d {{ .DIR }} ]]"
    cmds:
      - mkdir -p {{ .DIR }}

  helper/copy-config-file:
    label: copy-config-file[{{ .DESTINATION }}]
    internal: true
    cmds:
      - task: helper/ensure-config-file-dir
        vars:
          FILE: "{{ .DESTINATION }}"
      - mv -vf '{{ .DESTINATION }}' '{{ .BACKUP }}' || true
      - cp -va '{{ .SOURCE }}' '{{ .DESTINATION }}'
    status:
      - diff '{{ .SOURCE }}' '{{ .DESTINATION }}'

  helper/show-diff:
    internal: true
    vars:
      HELPER:
        sh: |
          if type delta > /dev/null; then
            echo '| delta'
          fi
    cmds:
      - |
        if [[ ! -f '{{ .OLD }}' ]]; then
          echo 'Left side ({{ .OLD }}) not exists'
        elif [[ ! -f '{{ .NEW }}' ]]; then
          echo 'Right side ({{ .NEW }}) not exists'
        else
          diff -u '{{ .OLD }}' '{{ .NEW }}' {{ .HELPER }}
        fi

  helper/ensure-ipython:
    cmds:
      - pipx install ipython
    status:
      - "[[ -x '{{ .PATH_LOCAL_BIN }}/ipython' ]]"

  # bat
  # ---------------------------------------------------------------------------
  install/bat/config:
    desc: Install bat config
    cmds:
      - task: helper/copy-config-dir
        vars:
          NAME: bat

  # git
  # ---------------------------------------------------------------------------
  install/git/config:
    desc: Install git config
    cmds:
      - task: diff/git/config
      - task: helper/copy-config-file
        vars:
          SOURCE: file/gitconfig
          DESTINATION: "{{ .HOME }}/.gitconfig"
          BACKUP: "{{ .HOME }}/.bak.gitconfig"
      - task: install/git/gitignore

  install/git/gitignore:
    cmds:
      - mkdir -p {{ .PATH_CONFIG }}/git
      - curl https://www.toptal.com/developers/gitignore/api/macos > {{ .PATH_CONFIG }}/git/macOS.gitignore
      - git config --global core.excludesfile {{ .PATH_CONFIG }}/git/macOS.gitignore

  diff/git/config:
    desc: Show git config diff between the currently used one and the one in this repo
    cmds:
      - task: helper/show-diff
        vars:
          NEW: file/gitconfig
          OLD: "{{ .HOME }}/.gitconfig"

  collect/git/config:
    desc: Collect git configs
    cmds:
      - cp -va '{{ .HOME }}/.gitconfig' 'file/gitconfig'

  # k9s
  # ---------------------------------------------------------------------------
  install/k9s/config:
    desc: Install k9s config
    cmds:
      - task: helper/copy-config-dir
        vars:
          NAME: k9s
          DIR: "{{ .PATH_APPLICATION_SUPPORT }}"

  diff/k9s/config:
    desc: Show k9s config diff between the currently used one and the one in this repo
    cmds:
      - task: helper/show-diff
        vars:
          NEW: config/k9s/config.yml
          OLD: "{{ .PATH_APPLICATION_SUPPORT }}/k9s/config.yml"

  collect/k9s/config:
    desc: Collect k9s configs
    cmds:
      - cp -va '{{ .PATH_APPLICATION_SUPPORT }}/k9s/config.yml' 'config/k9s/config.yml'

  # neovim
  # ---------------------------------------------------------------------------
  install/neovim/env:
    desc: Setup neovim environment
    deps:
      - task: helper/checkout-submodule
        vars:
          DIR: config/nvim/vim-plug
      - install/neovim/config
    cmds:
      - task: helper/copy-config-dir
        vars:
          NAME: nvim
      - task: helper/install-neovim-autoload

  helper/install-neovim-autoload:
    internal: true
    vars:
      PATH_AUTOLOAD: "{{ .PATH_LOCAL }}/share/nvim/site/autoload"
      TARGET: "{{ .PATH_AUTOLOAD }}/plug.vim"
    cmds:
      - mkdir -p {{ .PATH_AUTOLOAD }}
      - ln -s '{{ .PATH_CONFIG }}/nvim/vim-plug/plug.vim' '{{ .TARGET }}'
    status:
      - "[[ -L {{ .TARGET }} ]]"

  install/neovim/config:
    cmds:
      - task: diff/neovim/config
      - task: helper/copy-config-file
        vars:
          SOURCE: config/nvim/init.vim
          DESTINATION: "{{ .PATH_CONFIG }}/nvim/init.vim"
          BACKUP: "{{ .PATH_CONFIG }}/nvim/init.bak.vim"
      - task: update/neovim/plugin

  diff/neovim/config:
    desc: Show neovim config diff between the currently used one and the one in this repo
    cmds:
      - task: helper/show-diff
        vars:
          NEW: config/nvim/init.vim
          OLD: "{{ .PATH_CONFIG }}/nvim/init.vim"

  collect/neovim/config:
    desc: Collect neovim config
    cmds:
      - cp -va '{{ .PATH_CONFIG }}/nvim/init.vim' 'config/nvim/init.vim'

  update/neovim/plugin:
    desc: Update neovim plugins
    interactive: true
    cmds:
      - nvim '+PlugUpdate!' '+qall!'

  # tmux
  # ---------------------------------------------------------------------------
  install/tmux/env:
    desc: Install tmux config
    deps:
      - task: helper/checkout-submodule
        vars:
          DIR: config/tmux/tmux-sensible
      - task: helper/checkout-submodule
        vars:
          DIR: config/tmux/tmux-yank
    cmds:
      - task: helper/copy-config-dir
        vars:
          NAME: tmux

  collect/tmux/config:
    desc: Collect tmux config
    cmds:
      - cp -va {{ .PATH_CONFIG }}/tmux/*.tmux config/tmux/

  # toolkit
  # ---------------------------------------------------------------------------
  install/toolkit/python-tools:
    desc: Install some python-based utilities
    cmds:
      - pipx upgrade --install awscli
      - pipx upgrade --install bump2version
      - pipx upgrade --install bumpver
      - |
        pipx upgrade --install poetry
        pipx inject poetry 'secrets.env[all]'
      - pipx upgrade --install tldr
      - pipx upgrade --install uv

  install/toolkit/repo-scripts:
    desc: Install scripts from `bin/` directory in this directory
    deps:
      - task: helper/local-dir
    cmds:
      - cp -va bin/* '{{ .PATH_LOCAL_BIN }}/'

  helper/local-dir:
    internal: true
    cmds:
      - mkdir -p {{ .PATH_LOCAL }}
      - mkdir -p {{ .PATH_LOCAL_BIN }}
    status:
      - "[[ -d {{ .PATH_LOCAL_BIN }} ]]"

  # python
  # ---------------------------------------------------------------------------
  install/python/playground:
    desc: Create python playground
    deps:
      - task: helper/ensure-ipython
    cmds:
      - |-
        pipx inject ipython --pip-args='--upgrade' \
          beautifulsoup4    \
          'httpx[cli]'      \
          ipython           \
          jupyterlab        \
          lxml              \
          pandas            \
          python-dateutil   \
          pyyaml            \
          requests          \
          tabulate          \
          tqdm

  # zsh
  # ---------------------------------------------------------------------------
  install/zsh/env:
    desc: Setup zsh environment
    deps:
      - task: helper/checkout-submodule
        vars:
          DIR: config/zsh/bin
    cmds:
      - task: helper/copy-config-dir
        vars:
          NAME: zsh
      - task: install/zsh/config

  install/zsh/config:
    cmds:
      - task: diff/zsh/config
      - task: helper/copy-config-file
        vars:
          SOURCE: file/zshrc.zsh
          DESTINATION: "{{ .HOME }}/.zshrc"
          BACKUP: "{{ .HOME }}/.zshrc.bak.zsh"

  diff/zsh/config:
    desc: Show zsh config diff between the currently used one and the one in this repo
    cmds:
      - task: helper/show-diff
        vars:
          NEW: file/zshrc.zsh
          OLD: "{{ .HOME }}/.zshrc"

  collect/zsh/config:
    desc: Collect zsh config
    cmds:
      - cp -va "$HOME/.zshrc" 'file/zshrc.zsh'

  update/zsh/plugin:
    desc: Update zsh plugins
    cmds:
      - zinit update
