# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.config/zsh/oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="clover/clover"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/.config/zsh"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  fast-syntax-highlighting
  github
  calc
  colored-man-pages
  man
  wd
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
#export LANG=zh_TW.UTF-8
#export LC_ALL=zh_TW.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/id_ed25519"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias du='du -h -d1'
alias df='df -h'
alias vi=vim

# htop
if type htop > /dev/null; then
    alias top=htop
fi

# tmux
if type tmux > /dev/null; then
    TMUX_BIN=`which tmux`
    alias tmux-inner="$TMUX_BIN -f $HOME/.config/tmux/tmux-inner.conf -S /tmp/tmux-$(id -u)-inner"
    if [[ -n $TMUX ]] then
        alias tmux="tmux-inner"
    else
        alias tmux="$TMUX_BIN -f $HOME/.config/tmux/tmux.conf"
    fi
fi

# pipenv
export PIPENV_SHELL_FANCY=1
export PIPENV_VENV_IN_PROJECT=1

# temp dir
cdtemp() {
    export OLD_DIR="$(pwd)"
    export TEMP_DIR="$(mktemp -d)"

    cd "$TEMP_DIR"

    exittemp() {
        cd "$OLD_DIR"
        rm -rf "$TEMP_DIR"
        unset OLD_DIR
        unset TEMP_DIR
    }
}

# colorize less
SRC_HILIGHT='src-hilite-lesspipe.sh'

if type pygmentize > /dev/null; then
    export LESSOPEN="| $(which pygmentize) %s 2> /dev/null"
elif type $SRC_HILIGHT > /dev/null; then
    export LESSOPEN="| $(which $SRC_HILIGHT) %s"
fi

less () {
    env \
        LESS_TERMCAP_so="$(printf '\e[1;44;33m')" \
        LESS_TERMCAP_se="$(printf '\e[0m')" \
        less -i "$@"
}

# diff pager
if type diff-so-fancy > /dev/null; then
    diffp() {
        diff -u "$1" "$2" | diff-so-fancy | less
    }
fi

# rsync
if type rsync > /dev/null; then
    alias rsync='rsync -rlptD -hhh --progress'
fi
